-- ============================================================
-- Voyage Platform - 性能测试 + 造数引擎 + 资源核查 模块建表 V1.1
-- 数据库: PostgreSQL 16+
-- 说明: 由 Flyway 在应用启动时自动执行，禁止手工执行
-- ============================================================

-- -----------------------------------------------------------
-- 通用触发器函数: 模拟 MySQL 的 ON UPDATE CURRENT_TIMESTAMP
-- 带 last_time 字段的表使用此函数
-- -----------------------------------------------------------
CREATE OR REPLACE FUNCTION set_last_time()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_time = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 第一部分：公共依赖表
-- ============================================================

-- 1. 假日信息表 (性能测试场景日期计算依赖)
DROP TABLE IF EXISTS com_workholiday;
CREATE TABLE com_workholiday (
  date   DATE         NOT NULL,
  status VARCHAR(255) DEFAULT NULL,
  msg    VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (date)
);

COMMENT ON TABLE com_workholiday IS '假日信息表';
COMMENT ON COLUMN com_workholiday.date IS '日期';
COMMENT ON COLUMN com_workholiday.status IS '状态，0 放假 1 上班';
COMMENT ON COLUMN com_workholiday.msg IS '节日信息';

-- 2. 部署方案环境资源清单表 (资源核查 + 性能测试共用)
DROP TABLE IF EXISTS performance_resource_info;
CREATE TABLE performance_resource_info (
  id                               INTEGER GENERATED BY DEFAULT AS IDENTITY,
  serial_number                    INTEGER       DEFAULT NULL,
  task_name                        VARCHAR(255)  DEFAULT NULL,
  task_num                         VARCHAR(32)   DEFAULT NULL,
  service_name                     VARCHAR(255)  DEFAULT NULL,
  english_short_name               VARCHAR(100)  DEFAULT NULL,
  batch_name                       VARCHAR(32)   DEFAULT NULL,
  business_dept                    VARCHAR(100)  DEFAULT NULL,
  project_type                     VARCHAR(32)   DEFAULT NULL,
  disaster_backup_level            VARCHAR(32)   DEFAULT NULL,
  availability_level               VARCHAR(32)   DEFAULT NULL,
  deployment_location              VARCHAR(32)   DEFAULT NULL,
  network_deployment               VARCHAR(32)   DEFAULT NULL,
  system_platform                  VARCHAR(32)   DEFAULT NULL,
  paas_platform_type               VARCHAR(32)   DEFAULT NULL,
  theme_count                      INTEGER       DEFAULT NULL,
  queue_count                      INTEGER       DEFAULT NULL,
  shard_count                      INTEGER       DEFAULT NULL,
  per_shard_capacity_gb            INTEGER       DEFAULT NULL,
  redundancy_method                VARCHAR(32)   DEFAULT NULL,
  operating_system                 VARCHAR(255)  DEFAULT NULL,
  middleware                       VARCHAR(255)  DEFAULT NULL,
  partition_usage                  VARCHAR(100)  DEFAULT NULL,
  partition_usage_name             VARCHAR(100)  DEFAULT NULL,
  hostname                         VARCHAR(32)   DEFAULT NULL,
  ip_address                       VARCHAR(32)   DEFAULT NULL,
  backup_ip                        VARCHAR(32)   DEFAULT NULL,
  cpu_cores                        INTEGER       DEFAULT NULL,
  memory_gb                        INTEGER       DEFAULT NULL,
  dedicated_storage_gb             INTEGER       DEFAULT NULL,
  shared_storage_id                VARCHAR(32)   DEFAULT NULL,
  san_storage_gb                   INTEGER       DEFAULT NULL,
  nas_storage_gb                   INTEGER       DEFAULT NULL,
  signature_server                 VARCHAR(32)   DEFAULT NULL,
  encryption_device                VARCHAR(32)   DEFAULT NULL,
  load_balancer                    VARCHAR(32)   DEFAULT NULL,
  ssl_accelerator                  VARCHAR(32)   DEFAULT NULL,
  remarks                          VARCHAR(2000) DEFAULT NULL,
  partition_role                   VARCHAR(100)  DEFAULT NULL,
  revision_time                    TIMESTAMP     DEFAULT NULL,
  middleware_reason_below_baseline VARCHAR(255)  DEFAULT NULL,
  os_reason_below_baseline         VARCHAR(255)  DEFAULT NULL,
  resource_pool                    VARCHAR(255)  DEFAULT NULL,
  original_file_name               VARCHAR(255)  DEFAULT NULL,
  file_name                        VARCHAR(255)  DEFAULT NULL,
  product_id                       VARCHAR(32)   DEFAULT NULL,
  batch_no                         VARCHAR(32)   NOT NULL,
  file_source                      VARCHAR(32)   DEFAULT NULL,
  create_time                      TIMESTAMP     DEFAULT NULL,
  create_operator                  VARCHAR(32)   DEFAULT NULL,
  last_time                        TIMESTAMP     DEFAULT NULL,
  last_operator                    VARCHAR(32)   DEFAULT NULL,
  PRIMARY KEY (id)
);

COMMENT ON TABLE performance_resource_info IS '部署方案环境资源清单表';
COMMENT ON COLUMN performance_resource_info.id IS '主键ID';
COMMENT ON COLUMN performance_resource_info.serial_number IS '序号';
COMMENT ON COLUMN performance_resource_info.task_name IS '任务名称';
COMMENT ON COLUMN performance_resource_info.task_num IS '任务编号';
COMMENT ON COLUMN performance_resource_info.service_name IS '服务名称';
COMMENT ON COLUMN performance_resource_info.english_short_name IS '英文简称';
COMMENT ON COLUMN performance_resource_info.batch_name IS '批次名称';
COMMENT ON COLUMN performance_resource_info.business_dept IS '业务部门';
COMMENT ON COLUMN performance_resource_info.project_type IS '项目类型';
COMMENT ON COLUMN performance_resource_info.disaster_backup_level IS '灾备等级';
COMMENT ON COLUMN performance_resource_info.availability_level IS '可用性等级';
COMMENT ON COLUMN performance_resource_info.deployment_location IS '部署地点';
COMMENT ON COLUMN performance_resource_info.network_deployment IS '网络部署';
COMMENT ON COLUMN performance_resource_info.system_platform IS '系统平台';
COMMENT ON COLUMN performance_resource_info.paas_platform_type IS 'PAAS平台类型';
COMMENT ON COLUMN performance_resource_info.theme_count IS '主题数量';
COMMENT ON COLUMN performance_resource_info.queue_count IS '队列数量';
COMMENT ON COLUMN performance_resource_info.shard_count IS '分片数量';
COMMENT ON COLUMN performance_resource_info.per_shard_capacity_gb IS '每分片容量（G）';
COMMENT ON COLUMN performance_resource_info.redundancy_method IS '冗余方式';
COMMENT ON COLUMN performance_resource_info.operating_system IS '操作系统';
COMMENT ON COLUMN performance_resource_info.middleware IS '中间件';
COMMENT ON COLUMN performance_resource_info.partition_usage IS '分区用途';
COMMENT ON COLUMN performance_resource_info.partition_usage_name IS '分区用途名称';
COMMENT ON COLUMN performance_resource_info.hostname IS '主机名';
COMMENT ON COLUMN performance_resource_info.ip_address IS 'IP地址';
COMMENT ON COLUMN performance_resource_info.backup_ip IS '数据备份IP';
COMMENT ON COLUMN performance_resource_info.cpu_cores IS 'CPU核心数';
COMMENT ON COLUMN performance_resource_info.memory_gb IS '内存（GB）';
COMMENT ON COLUMN performance_resource_info.dedicated_storage_gb IS '独占存储（GB）';
COMMENT ON COLUMN performance_resource_info.shared_storage_id IS '共享存储编号';
COMMENT ON COLUMN performance_resource_info.san_storage_gb IS 'SAN存储（GB）';
COMMENT ON COLUMN performance_resource_info.nas_storage_gb IS 'NAS存储（GB）';
COMMENT ON COLUMN performance_resource_info.signature_server IS '是否有签名服务器';
COMMENT ON COLUMN performance_resource_info.encryption_device IS '是否有加密机';
COMMENT ON COLUMN performance_resource_info.load_balancer IS '是否有负载均衡器';
COMMENT ON COLUMN performance_resource_info.ssl_accelerator IS '是否有SSL加速器';
COMMENT ON COLUMN performance_resource_info.remarks IS '备注（外设型号）';
COMMENT ON COLUMN performance_resource_info.partition_role IS '分区角色';
COMMENT ON COLUMN performance_resource_info.revision_time IS '修订时间';
COMMENT ON COLUMN performance_resource_info.middleware_reason_below_baseline IS '中间件使用低于基线版本原因';
COMMENT ON COLUMN performance_resource_info.os_reason_below_baseline IS '操作系统使用低于基线版本原因';
COMMENT ON COLUMN performance_resource_info.resource_pool IS '资源池';
COMMENT ON COLUMN performance_resource_info.original_file_name IS '原始文件名';
COMMENT ON COLUMN performance_resource_info.file_name IS '上传文件名';
COMMENT ON COLUMN performance_resource_info.product_id IS '产品标识';
COMMENT ON COLUMN performance_resource_info.batch_no IS '性能测试任务-批次 (如：2606)';
COMMENT ON COLUMN performance_resource_info.file_source IS '文件来源：部署方案 / 资源申请表';
COMMENT ON COLUMN performance_resource_info.create_time IS '创建时间';
COMMENT ON COLUMN performance_resource_info.create_operator IS '创建人';
COMMENT ON COLUMN performance_resource_info.last_time IS '更新时间';
COMMENT ON COLUMN performance_resource_info.last_operator IS '更新人';

CREATE TRIGGER trg_performance_resource_info_last_time
BEFORE UPDATE ON performance_resource_info
FOR EACH ROW EXECUTE FUNCTION set_last_time();

-- ============================================================
-- 第二部分：性能测试模块 (10 张表)
-- ============================================================

-- 3. 性能测试任务主表
DROP TABLE IF EXISTS perf_task;
CREATE TABLE perf_task (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  product_id               VARCHAR(64)   NOT NULL,
  batch_no                 VARCHAR(32)   NOT NULL,
  task_name                VARCHAR(255)  DEFAULT NULL,
  test_task_no             VARCHAR(64)   DEFAULT NULL,
  prod_task_no             VARCHAR(64)   DEFAULT NULL,
  req_no                   VARCHAR(64)   DEFAULT NULL,
  proj_name                VARCHAR(255)  DEFAULT NULL,
  proj_no                  VARCHAR(64)   DEFAULT NULL,
  test_dept                VARCHAR(128)  DEFAULT NULL,
  dev_dept                 VARCHAR(128)  DEFAULT NULL,
  start_time               TIMESTAMP     DEFAULT NULL,
  end_time                 TIMESTAMP     DEFAULT NULL,
  perf_manager             VARCHAR(64)   DEFAULT NULL,
  test_arch                VARCHAR(64)   DEFAULT NULL,
  project_manager          VARCHAR(64)   DEFAULT NULL,
  recorder_range           TEXT          DEFAULT NULL,
  creator_id               VARCHAR(7)    NOT NULL,
  status                   INTEGER       DEFAULT 10,
  total_user_count         NUMERIC(12,4) DEFAULT NULL,
  daily_online_user_count  NUMERIC(12,4) DEFAULT NULL,
  daily_peak_tps           NUMERIC(10,3) DEFAULT NULL,
  annual_peak_tps          NUMERIC(10,3) DEFAULT NULL,
  selected_tran_tps_sum    NUMERIC(10,3) DEFAULT NULL,
  batch_total_duration     VARCHAR(64)   DEFAULT NULL,
  batch_total_data_volume  VARCHAR(128)  DEFAULT NULL,
  batch_parallel_degree    VARCHAR(64)   DEFAULT NULL,
  batch_max_parallel_count VARCHAR(32)   DEFAULT NULL,
  create_time              TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_time                TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_task IS '性能测试任务主表';
COMMENT ON COLUMN perf_task.id IS '主键ID';
COMMENT ON COLUMN perf_task.product_id IS '产品/牵头组件标识 (如：BPS-D-AUTO)';
COMMENT ON COLUMN perf_task.batch_no IS '批次 (如：2606)';
COMMENT ON COLUMN perf_task.task_name IS '任务名称';
COMMENT ON COLUMN perf_task.test_task_no IS '测试任务编号';
COMMENT ON COLUMN perf_task.prod_task_no IS '生产任务编号';
COMMENT ON COLUMN perf_task.req_no IS '需求编号';
COMMENT ON COLUMN perf_task.proj_name IS '项目名称';
COMMENT ON COLUMN perf_task.proj_no IS '项目编号';
COMMENT ON COLUMN perf_task.test_dept IS '测试部门';
COMMENT ON COLUMN perf_task.dev_dept IS '开发部门';
COMMENT ON COLUMN perf_task.start_time IS '测试开始时间';
COMMENT ON COLUMN perf_task.end_time IS '测试结束时间';
COMMENT ON COLUMN perf_task.perf_manager IS '性能测试经理姓名';
COMMENT ON COLUMN perf_task.test_arch IS '测试架构师姓名';
COMMENT ON COLUMN perf_task.project_manager IS '项目经理姓名';
COMMENT ON COLUMN perf_task.recorder_range IS '填报人员范围 (7位员工号，逗号分隔)';
COMMENT ON COLUMN perf_task.creator_id IS '创建人ID (7位员工号)';
COMMENT ON COLUMN perf_task.status IS '任务状态 (10:新建/调研中, 20:方案待明确, 30:已定稿)';
COMMENT ON COLUMN perf_task.total_user_count IS '用户数总数';
COMMENT ON COLUMN perf_task.daily_online_user_count IS '日均在线用户数';
COMMENT ON COLUMN perf_task.daily_peak_tps IS '日交易峰值TPS';
COMMENT ON COLUMN perf_task.annual_peak_tps IS '年交易峰值TPS';
COMMENT ON COLUMN perf_task.selected_tran_tps_sum IS '选中交易TPS之和';
COMMENT ON COLUMN perf_task.batch_total_duration IS '预估整体批量时长';
COMMENT ON COLUMN perf_task.batch_total_data_volume IS '预估整体数据量';
COMMENT ON COLUMN perf_task.batch_parallel_degree IS '并行度';
COMMENT ON COLUMN perf_task.batch_max_parallel_count IS '最大并行数';
COMMENT ON COLUMN perf_task.create_time IS '创建时间';
COMMENT ON COLUMN perf_task.last_time IS '最后更新时间';

CREATE INDEX idx_perf_task_batch_product ON perf_task (batch_no, product_id);
CREATE INDEX idx_perf_task_creator ON perf_task (creator_id);

CREATE TRIGGER trg_perf_task_last_time
BEFORE UPDATE ON perf_task
FOR EACH ROW EXECUTE FUNCTION set_last_time();

-- 4. 联机交易调研与指标方案表
DROP TABLE IF EXISTS perf_task_tran;
CREATE TABLE perf_task_tran (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
  task_id               BIGINT        NOT NULL,
  module_name           VARCHAR(64)   DEFAULT NULL,
  tran_name             VARCHAR(128)  NOT NULL,
  tran_code             VARCHAR(128)  DEFAULT NULL,
  interface_type        VARCHAR(64)   DEFAULT NULL,
  tran_daily_vol        NUMERIC(12,4) DEFAULT NULL,
  tran_peak_hour_vol    NUMERIC(12,4) DEFAULT NULL,
  tran_peak_tps         NUMERIC(10,3) DEFAULT NULL,
  tran_avg_rt           NUMERIC(10,3) DEFAULT NULL,
  tran_max_rt           NUMERIC(10,3) DEFAULT NULL,
  target_daily_vol      NUMERIC(12,4) DEFAULT NULL,
  target_peak_hour_vol  NUMERIC(12,4) DEFAULT NULL,
  target_tps            NUMERIC(10,3) DEFAULT NULL,
  target_rt             NUMERIC(10,3) DEFAULT NULL,
  target_max_rt         NUMERIC(10,3) DEFAULT NULL,
  target_success_rate   NUMERIC(5,2)  DEFAULT 100.00,
  target_think_time     NUMERIC(10,3) DEFAULT NULL,
  is_selected           SMALLINT      DEFAULT 1,
  select_reason         VARCHAR(512)  DEFAULT NULL,
  indicator_source      INTEGER       DEFAULT 1,
  calculation_process   TEXT          DEFAULT NULL,
  create_time           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_time             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_task_tran IS '联机交易调研与指标方案表';
COMMENT ON COLUMN perf_task_tran.id IS '主键ID';
COMMENT ON COLUMN perf_task_tran.task_id IS '关联主表perf_task的id';
COMMENT ON COLUMN perf_task_tran.module_name IS '产品名称/模块名称';
COMMENT ON COLUMN perf_task_tran.tran_name IS '交易名称';
COMMENT ON COLUMN perf_task_tran.tran_code IS '交易代码/apicode';
COMMENT ON COLUMN perf_task_tran.interface_type IS '用户群说明/接口类型';
COMMENT ON COLUMN perf_task_tran.tran_daily_vol IS '生产日峰值交易量(万笔/日)';
COMMENT ON COLUMN perf_task_tran.tran_peak_hour_vol IS '生产高峰时段量(万笔/小时)';
COMMENT ON COLUMN perf_task_tran.tran_peak_tps IS '生产每秒最大TPS';
COMMENT ON COLUMN perf_task_tran.tran_avg_rt IS '生产平均响应时间(秒)';
COMMENT ON COLUMN perf_task_tran.tran_max_rt IS '生产最大响应时间(秒)';
COMMENT ON COLUMN perf_task_tran.target_daily_vol IS '目标日峰值量(万笔/日)';
COMMENT ON COLUMN perf_task_tran.target_peak_hour_vol IS '目标高峰时段量(万笔/小时)';
COMMENT ON COLUMN perf_task_tran.target_tps IS '测试目标TPS';
COMMENT ON COLUMN perf_task_tran.target_rt IS '目标平均响应时间(秒)';
COMMENT ON COLUMN perf_task_tran.target_max_rt IS '目标最大响应时间(秒)';
COMMENT ON COLUMN perf_task_tran.target_success_rate IS '目标交易成功率(%)';
COMMENT ON COLUMN perf_task_tran.target_think_time IS '用户平均操作时间/思考时间(秒)';
COMMENT ON COLUMN perf_task_tran.is_selected IS '是否选为性能测试交易';
COMMENT ON COLUMN perf_task_tran.select_reason IS '选取原因(多选枚举，含复杂度说明)';
COMMENT ON COLUMN perf_task_tran.indicator_source IS '指标来源(1:实测, 2:采样折算, 3:经验对标)';
COMMENT ON COLUMN perf_task_tran.calculation_process IS '指标推算过程';
COMMENT ON COLUMN perf_task_tran.create_time IS '创建时间';
COMMENT ON COLUMN perf_task_tran.last_time IS '最后更新时间';

CREATE INDEX idx_perf_task_tran_task_id ON perf_task_tran (task_id);

CREATE TRIGGER trg_perf_task_tran_last_time
BEFORE UPDATE ON perf_task_tran
FOR EACH ROW EXECUTE FUNCTION set_last_time();

-- 5. 批量作业调研与指标方案表
DROP TABLE IF EXISTS perf_task_batch;
CREATE TABLE perf_task_batch (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  task_id              BIGINT       NOT NULL,
  job_no               VARCHAR(32)  DEFAULT NULL,
  job_name             VARCHAR(128) NOT NULL,
  job_count            VARCHAR(32)  DEFAULT '1',
  job_parallel_mode    VARCHAR(64)  DEFAULT NULL,
  job_desc             TEXT         DEFAULT NULL,
  job_trigger_cond     VARCHAR(255) DEFAULT NULL,
  job_pre_name         VARCHAR(255) DEFAULT NULL,
  job_concurrent_names TEXT         DEFAULT NULL,
  job_frequency        VARCHAR(32)  DEFAULT NULL,
  job_data_type        VARCHAR(64)  DEFAULT NULL,
  job_data_volume      VARCHAR(128) DEFAULT NULL,
  job_actual_duration  VARCHAR(64)  DEFAULT NULL,
  job_duration         VARCHAR(64)  DEFAULT NULL,
  job_exec_time_point  VARCHAR(255) DEFAULT NULL,
  is_mixed_link        VARCHAR(16)  DEFAULT '否',
  mixed_tran_names     VARCHAR(255) DEFAULT NULL,
  has_retry            VARCHAR(64)  DEFAULT '是',
  retry_desc           TEXT         DEFAULT NULL,
  select_reason        VARCHAR(512) DEFAULT NULL,
  create_time          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_time            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_task_batch IS '批量作业调研与指标方案表';
COMMENT ON COLUMN perf_task_batch.id IS '主键ID';
COMMENT ON COLUMN perf_task_batch.task_id IS '关联主表perf_task的id';
COMMENT ON COLUMN perf_task_batch.job_no IS '作业编号';
COMMENT ON COLUMN perf_task_batch.job_name IS '批量作业名称';
COMMENT ON COLUMN perf_task_batch.job_count IS '批量作业数';
COMMENT ON COLUMN perf_task_batch.job_parallel_mode IS '并行方式';
COMMENT ON COLUMN perf_task_batch.job_desc IS '批量作业功能简述';
COMMENT ON COLUMN perf_task_batch.job_trigger_cond IS '触发条件';
COMMENT ON COLUMN perf_task_batch.job_pre_name IS '前导作业名';
COMMENT ON COLUMN perf_task_batch.job_concurrent_names IS '可同时并行作业名';
COMMENT ON COLUMN perf_task_batch.job_frequency IS '执行频率';
COMMENT ON COLUMN perf_task_batch.job_data_type IS '最大数据量级数据类型';
COMMENT ON COLUMN perf_task_batch.job_data_volume IS '预估数据量级';
COMMENT ON COLUMN perf_task_batch.job_actual_duration IS '生产调研实际运行时长';
COMMENT ON COLUMN perf_task_batch.job_duration IS '预估处理时长/性能要求时长';
COMMENT ON COLUMN perf_task_batch.job_exec_time_point IS '生产上批量执行时间点';
COMMENT ON COLUMN perf_task_batch.is_mixed_link IS '是否叠加联机交易';
COMMENT ON COLUMN perf_task_batch.mixed_tran_names IS '叠加联机交易名称';
COMMENT ON COLUMN perf_task_batch.has_retry IS '是否有重做机制';
COMMENT ON COLUMN perf_task_batch.retry_desc IS '重做机制简述';
COMMENT ON COLUMN perf_task_batch.select_reason IS '选取原因';
COMMENT ON COLUMN perf_task_batch.create_time IS '创建时间';
COMMENT ON COLUMN perf_task_batch.last_time IS '最后更新时间';

CREATE INDEX idx_perf_task_batch_task_id ON perf_task_batch (task_id);

CREATE TRIGGER trg_perf_task_batch_last_time
BEFORE UPDATE ON perf_task_batch
FOR EACH ROW EXECUTE FUNCTION set_last_time();

-- 6. 性能测试数据准备方案主表(定性描述)
DROP TABLE IF EXISTS perf_data_plan;
CREATE TABLE perf_data_plan (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  task_id           BIGINT   NOT NULL,
  model_analysis    TEXT     DEFAULT NULL,
  data_constraint   TEXT     DEFAULT NULL,
  data_source_desc  TEXT     DEFAULT NULL,
  prep_method_desc  TEXT     DEFAULT NULL,
  cleaning_rule     TEXT     DEFAULT NULL,
  create_time       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_time         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_perf_data_plan_task_id UNIQUE (task_id)
);

COMMENT ON TABLE perf_data_plan IS '性能测试数据准备方案主表(定性描述)';
COMMENT ON COLUMN perf_data_plan.id IS '主键ID';
COMMENT ON COLUMN perf_data_plan.task_id IS '关联性能任务ID';
COMMENT ON COLUMN perf_data_plan.model_analysis IS '相关数据内容分析';
COMMENT ON COLUMN perf_data_plan.data_constraint IS '数据约束说明';
COMMENT ON COLUMN perf_data_plan.data_source_desc IS '数据来源说明';
COMMENT ON COLUMN perf_data_plan.prep_method_desc IS '数据构造/准备方法描述';
COMMENT ON COLUMN perf_data_plan.cleaning_rule IS '数据脱敏/清洗规则';
COMMENT ON COLUMN perf_data_plan.create_time IS '创建时间';
COMMENT ON COLUMN perf_data_plan.last_time IS '最后更新时间';

CREATE TRIGGER trg_perf_data_plan_last_time
BEFORE UPDATE ON perf_data_plan
FOR EACH ROW EXECUTE FUNCTION set_last_time();

-- 7. 性能测试数据准备明细表(表级规模)
DROP TABLE IF EXISTS perf_data_detail;
CREATE TABLE perf_data_detail (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  task_id           BIGINT        NOT NULL,
  data_type         INTEGER       DEFAULT 1,
  table_name_en     VARCHAR(128)  NOT NULL,
  table_name_cn     VARCHAR(128)  DEFAULT NULL,
  table_rows_count  BIGINT        DEFAULT NULL,
  table_growth_rate NUMERIC(5,2)  DEFAULT NULL,
  target_rows_count BIGINT        DEFAULT NULL,
  data_dist_desc    TEXT          DEFAULT NULL,
  prep_method       VARCHAR(64)   DEFAULT '脚本自造',
  create_time       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_time         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_data_detail IS '性能测试数据准备明细表(表级规模)';
COMMENT ON COLUMN perf_data_detail.id IS '主键ID';
COMMENT ON COLUMN perf_data_detail.task_id IS '关联性能任务ID';
COMMENT ON COLUMN perf_data_detail.data_type IS '数据分类(1:核心业务表, 2:基础数据/码表)';
COMMENT ON COLUMN perf_data_detail.table_name_en IS '英文表名';
COMMENT ON COLUMN perf_data_detail.table_name_cn IS '中文表名/描述';
COMMENT ON COLUMN perf_data_detail.table_rows_count IS '生产当前存量行数(万行)';
COMMENT ON COLUMN perf_data_detail.table_growth_rate IS '预估年增长率(%)';
COMMENT ON COLUMN perf_data_detail.target_rows_count IS '测试目标造数行数(万行)';
COMMENT ON COLUMN perf_data_detail.data_dist_desc IS '数据量情况/数据特征分布';
COMMENT ON COLUMN perf_data_detail.prep_method IS '准备方式(生产脱敏借数/脚本自造)';
COMMENT ON COLUMN perf_data_detail.create_time IS '创建时间';
COMMENT ON COLUMN perf_data_detail.last_time IS '最后更新时间';

CREATE INDEX idx_perf_data_detail_task_id ON perf_data_detail (task_id);

CREATE TRIGGER trg_perf_data_detail_last_time
BEFORE UPDATE ON perf_data_detail
FOR EACH ROW EXECUTE FUNCTION set_last_time();

-- 8. 性能测试场景定义主表
DROP TABLE IF EXISTS perf_task_scene;
CREATE TABLE perf_task_scene (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
  task_id               BIGINT        NOT NULL,
  scene_type            INTEGER       NOT NULL,
  scene_name            VARCHAR(128)  NOT NULL,
  target_tps_ratio      NUMERIC(5,2)  DEFAULT 100.00,
  target_total_tps      NUMERIC(10,2) DEFAULT NULL,
  test_objective        TEXT          DEFAULT NULL,
  implementation_method TEXT          DEFAULT NULL,
  end_condition         TEXT          DEFAULT NULL,
  is_selected           SMALLINT      DEFAULT 1,
  global_duration       INTEGER       DEFAULT NULL,
  create_time           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_task_scene IS '性能测试场景定义主表';
COMMENT ON COLUMN perf_task_scene.id IS '主键ID';
COMMENT ON COLUMN perf_task_scene.task_id IS '关联主表id';
COMMENT ON COLUMN perf_task_scene.scene_type IS '1:基准, 2:单负载, 3:混合负载, 4:稳定性, 5:极限, 6:批量';
COMMENT ON COLUMN perf_task_scene.scene_name IS '场景名称';
COMMENT ON COLUMN perf_task_scene.target_tps_ratio IS '目标TPS百分比';
COMMENT ON COLUMN perf_task_scene.target_total_tps IS '目标总TPS值';
COMMENT ON COLUMN perf_task_scene.test_objective IS '测试目的';
COMMENT ON COLUMN perf_task_scene.implementation_method IS '实施方法';
COMMENT ON COLUMN perf_task_scene.end_condition IS '结束条件(主要针对极限测试)';
COMMENT ON COLUMN perf_task_scene.is_selected IS '是否勾选执行';
COMMENT ON COLUMN perf_task_scene.global_duration IS '全局预计持续时间(分)';
COMMENT ON COLUMN perf_task_scene.create_time IS '创建时间';
COMMENT ON COLUMN perf_task_scene.update_time IS '最后更新时间';

CREATE INDEX idx_perf_task_scene_task_id ON perf_task_scene (task_id);

CREATE TRIGGER trg_perf_task_scene_update_time
BEFORE UPDATE ON perf_task_scene
FOR EACH ROW EXECUTE FUNCTION set_update_time();

-- 9. 场景内交易配置明细表
DROP TABLE IF EXISTS perf_task_scene_detail;
CREATE TABLE perf_task_scene_detail (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
  scene_id            BIGINT        NOT NULL,
  tran_id             BIGINT        NOT NULL,
  tran_name           VARCHAR(128)  DEFAULT NULL,
  target_tps          NUMERIC(10,2) DEFAULT NULL,
  target_rt           NUMERIC(10,3) DEFAULT NULL,
  target_success_rate NUMERIC(5,2)  DEFAULT 100.00,
  vu_count            INTEGER       DEFAULT NULL,
  ramp_up             INTEGER       DEFAULT NULL,
  pacing              NUMERIC(10,2) DEFAULT NULL,
  throughput_timer    NUMERIC(10,2) DEFAULT NULL,
  iterations          INTEGER       DEFAULT NULL,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_task_scene_detail IS '场景内交易配置明细表';
COMMENT ON COLUMN perf_task_scene_detail.id IS '主键ID';
COMMENT ON COLUMN perf_task_scene_detail.scene_id IS '关联perf_task_scene.id';
COMMENT ON COLUMN perf_task_scene_detail.tran_id IS '关联perf_task_tran.id';
COMMENT ON COLUMN perf_task_scene_detail.tran_name IS '交易名称(冗余)';
COMMENT ON COLUMN perf_task_scene_detail.target_tps IS '预期目标TPS';
COMMENT ON COLUMN perf_task_scene_detail.target_rt IS '预期响应时间(秒)';
COMMENT ON COLUMN perf_task_scene_detail.target_success_rate IS '预期成功率(%)';
COMMENT ON COLUMN perf_task_scene_detail.vu_count IS '并发用户数';
COMMENT ON COLUMN perf_task_scene_detail.ramp_up IS '启动时间(秒)';
COMMENT ON COLUMN perf_task_scene_detail.pacing IS '迭代间隔';
COMMENT ON COLUMN perf_task_scene_detail.throughput_timer IS '常数吞吐量定时器配置';
COMMENT ON COLUMN perf_task_scene_detail.iterations IS '迭代次数';

CREATE INDEX idx_perf_task_scene_detail_scene_id ON perf_task_scene_detail (scene_id);

-- 10. 场景执行结果主表(记录压测轮次和时间轴)
DROP TABLE IF EXISTS perf_task_scene_result;
CREATE TABLE perf_task_scene_result (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  scene_id         BIGINT        NOT NULL,
  round_number     INTEGER       DEFAULT 1,
  test_env         VARCHAR(64)   DEFAULT NULL,
  run_status       INTEGER       DEFAULT 0,
  run_start_time   TIMESTAMP     DEFAULT NULL,
  run_end_time     TIMESTAMP     DEFAULT NULL,
  is_standard      SMALLINT      DEFAULT 0,
  actual_total_tps NUMERIC(10,2) DEFAULT NULL,
  result_status    INTEGER       DEFAULT 0,
  summary_remark   VARCHAR(512)  DEFAULT NULL,
  create_time      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_task_scene_result IS '场景执行结果主表(记录压测轮次和时间轴)';
COMMENT ON COLUMN perf_task_scene_result.id IS '主键ID';
COMMENT ON COLUMN perf_task_scene_result.scene_id IS '关联perf_task_scene.id';
COMMENT ON COLUMN perf_task_scene_result.round_number IS '轮次(第1轮, 第2轮...)';
COMMENT ON COLUMN perf_task_scene_result.test_env IS '执行环境';
COMMENT ON COLUMN perf_task_scene_result.run_status IS '执行状态(0:执行中, 1:已完成, 2:异常中断)';
COMMENT ON COLUMN perf_task_scene_result.run_start_time IS '压测实际开始时间';
COMMENT ON COLUMN perf_task_scene_result.run_end_time IS '压测实际结束时间';
COMMENT ON COLUMN perf_task_scene_result.is_standard IS '是否作为达标轮次(1:是, 0:否)';
COMMENT ON COLUMN perf_task_scene_result.actual_total_tps IS '本轮实测总TPS';
COMMENT ON COLUMN perf_task_scene_result.result_status IS '结果状态(0:未达标, 1:已达标, 2:待评审)';
COMMENT ON COLUMN perf_task_scene_result.summary_remark IS '执行总结';
COMMENT ON COLUMN perf_task_scene_result.create_time IS '创建时间';

CREATE INDEX idx_perf_task_scene_result_scene_id ON perf_task_scene_result (scene_id);

-- 11. 场景执行结果交易明细表(记录每轮各交易实测值)
DROP TABLE IF EXISTS perf_task_scene_result_detail;
CREATE TABLE perf_task_scene_result_detail (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
  result_id           BIGINT        NOT NULL,
  tran_id             BIGINT        NOT NULL,
  tran_name           VARCHAR(128)  DEFAULT NULL,
  actual_tps          NUMERIC(10,2) DEFAULT NULL,
  actual_rt           NUMERIC(10,3) DEFAULT NULL,
  actual_rt_90        NUMERIC(10,3) DEFAULT NULL,
  actual_rt_max       NUMERIC(10,3) DEFAULT NULL,
  actual_success_rate NUMERIC(5,2)  DEFAULT NULL,
  total_request_count BIGINT        DEFAULT NULL,
  actual_db_count     BIGINT        DEFAULT NULL,
  is_compliant        SMALLINT      DEFAULT 1,
  create_time         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_task_scene_result_detail IS '场景执行结果交易明细表(记录每轮各交易实测值)';
COMMENT ON COLUMN perf_task_scene_result_detail.id IS '主键ID';
COMMENT ON COLUMN perf_task_scene_result_detail.result_id IS '关联perf_task_scene_result.id';
COMMENT ON COLUMN perf_task_scene_result_detail.tran_id IS '关联perf_task_tran.id';
COMMENT ON COLUMN perf_task_scene_result_detail.tran_name IS '交易名称(冗余)';
COMMENT ON COLUMN perf_task_scene_result_detail.actual_tps IS '实测TPS';
COMMENT ON COLUMN perf_task_scene_result_detail.actual_rt IS '实测平均响应时间(s)';
COMMENT ON COLUMN perf_task_scene_result_detail.actual_rt_90 IS '实测90%响应时间(s)';
COMMENT ON COLUMN perf_task_scene_result_detail.actual_rt_max IS '实测最大响应时间(s)';
COMMENT ON COLUMN perf_task_scene_result_detail.actual_success_rate IS '实测成功率(%)';
COMMENT ON COLUMN perf_task_scene_result_detail.total_request_count IS '总请求笔数';
COMMENT ON COLUMN perf_task_scene_result_detail.actual_db_count IS '实际落表笔数';
COMMENT ON COLUMN perf_task_scene_result_detail.is_compliant IS '单交易是否达标(1:是, 0:否)';
COMMENT ON COLUMN perf_task_scene_result_detail.create_time IS '创建时间';

CREATE INDEX idx_perf_task_scene_result_detail_result_id ON perf_task_scene_result_detail (result_id);

-- 12. 性能测试数据信息表 (关联任务+批次的数据快照)
DROP TABLE IF EXISTS perf_task_data;
CREATE TABLE perf_task_data (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  task_id     BIGINT       NOT NULL,
  batch_name  VARCHAR(32)  DEFAULT NULL,
  data_label  VARCHAR(128) DEFAULT NULL,
  data_desc   TEXT         DEFAULT NULL,
  create_time TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_time   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE perf_task_data IS '性能测试数据信息表';
COMMENT ON COLUMN perf_task_data.id IS '主键ID';
COMMENT ON COLUMN perf_task_data.task_id IS '关联perf_task.id';
COMMENT ON COLUMN perf_task_data.batch_name IS '批次名称';
COMMENT ON COLUMN perf_task_data.data_label IS '数据标签';
COMMENT ON COLUMN perf_task_data.data_desc IS '数据描述';
COMMENT ON COLUMN perf_task_data.create_time IS '创建时间';
COMMENT ON COLUMN perf_task_data.last_time IS '最后更新时间';

CREATE INDEX idx_perf_task_data_task_id ON perf_task_data (task_id);

CREATE TRIGGER trg_perf_task_data_last_time
BEFORE UPDATE ON perf_task_data
FOR EACH ROW EXECUTE FUNCTION set_last_time();

-- ============================================================
-- 第三部分：造数引擎模块 (7 张表)
-- ============================================================

-- 13. 文件模型主表
DROP TABLE IF EXISTS meta_file_model;
CREATE TABLE meta_file_model (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
  model_name       VARCHAR(100) NOT NULL,
  has_header       SMALLINT     DEFAULT 1,
  has_footer       SMALLINT     DEFAULT 1,
  split_type       VARCHAR(20)  NOT NULL,
  delimiter        VARCHAR(10)  DEFAULT NULL,
  line_ending_char VARCHAR(10)  DEFAULT NULL,
  encoding         VARCHAR(20)  DEFAULT 'UTF-8',
  max_rows_limit   INTEGER      DEFAULT 10000,
  owner_id         VARCHAR(50)  NOT NULL,
  status           VARCHAR(20)  DEFAULT 'DRAFT',
  model_version    INTEGER      DEFAULT 1,
  shared_with      VARCHAR(100) DEFAULT NULL,
  create_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  update_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE meta_file_model IS '文件模型主表';
COMMENT ON COLUMN meta_file_model.id IS '主键ID';
COMMENT ON COLUMN meta_file_model.model_name IS '模型名称';
COMMENT ON COLUMN meta_file_model.has_header IS '是否有文件头：1-有，0-无';
COMMENT ON COLUMN meta_file_model.has_footer IS '是否有文件尾：1-有，0-无';
COMMENT ON COLUMN meta_file_model.split_type IS '分隔符或定长: DELIMITER / FIXED';
COMMENT ON COLUMN meta_file_model.delimiter IS '分隔符内容';
COMMENT ON COLUMN meta_file_model.line_ending_char IS '行结尾固定符号';
COMMENT ON COLUMN meta_file_model.encoding IS 'UTF-8/GBK';
COMMENT ON COLUMN meta_file_model.max_rows_limit IS '记录数安全阈值-超过则报错';
COMMENT ON COLUMN meta_file_model.owner_id IS '创建人ID-记录员工工号';
COMMENT ON COLUMN meta_file_model.status IS '模型状态: DRAFT/PUBLISHED/DISABLED';
COMMENT ON COLUMN meta_file_model.model_version IS '模型版本号';
COMMENT ON COLUMN meta_file_model.shared_with IS '共享用户ID逗号分隔';
COMMENT ON COLUMN meta_file_model.create_time IS '创建时间';
COMMENT ON COLUMN meta_file_model.update_time IS '最后更新时间';

CREATE TRIGGER trg_meta_file_model_update_time
BEFORE UPDATE ON meta_file_model
FOR EACH ROW EXECUTE FUNCTION set_update_time();

-- 14. 字段定义明细表
DROP TABLE IF EXISTS meta_field_definition;
CREATE TABLE meta_field_definition (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
  model_id          BIGINT      NOT NULL,
  section           VARCHAR(20) NOT NULL,
  parent_id         BIGINT      DEFAULT NULL,
  field_key         VARCHAR(50) NOT NULL,
  field_name        VARCHAR(100) DEFAULT NULL,
  sort_index        INTEGER     NOT NULL,
  level             SMALLINT    DEFAULT 1,
  length            INTEGER     NOT NULL,
  is_required       SMALLINT    NOT NULL DEFAULT 0,
  padding_direction VARCHAR(10) DEFAULT 'NONE',
  padding_char      VARCHAR(5)  DEFAULT ' ',
  rule_type         VARCHAR(30) NOT NULL,
  ref_field_key     VARCHAR(50) DEFAULT NULL,
  ref_enum_key      VARCHAR(50) DEFAULT NULL,
  ref_sequence_key  VARCHAR(50) DEFAULT NULL,
  ref_file_id       BIGINT      DEFAULT NULL,
  rule_config_json  JSONB       NOT NULL,
  PRIMARY KEY (id)
);

COMMENT ON TABLE meta_field_definition IS '字段定义明细表';
COMMENT ON COLUMN meta_field_definition.id IS '主键ID';
COMMENT ON COLUMN meta_field_definition.model_id IS '所属模型ID';
COMMENT ON COLUMN meta_field_definition.section IS '字段所属区域: FILENAME/HEADER/BODY/FOOTER';
COMMENT ON COLUMN meta_field_definition.parent_id IS '仅支持两层，子字段填父ID';
COMMENT ON COLUMN meta_field_definition.field_key IS '字段唯一变量名，供后面引用';
COMMENT ON COLUMN meta_field_definition.field_name IS '业务描述';
COMMENT ON COLUMN meta_field_definition.sort_index IS '后端真实排序依据';
COMMENT ON COLUMN meta_field_definition.level IS '字段层级：1-一级，2-二级';
COMMENT ON COLUMN meta_field_definition.length IS '定长模式下的字节/字符长度';
COMMENT ON COLUMN meta_field_definition.is_required IS '是否必填：1-是，0-否';
COMMENT ON COLUMN meta_field_definition.padding_direction IS '补位方向：LEFT/RIGHT/NONE';
COMMENT ON COLUMN meta_field_definition.padding_char IS '补位字符';
COMMENT ON COLUMN meta_field_definition.rule_type IS '规则类型: FIXED/DATE/ENUM/REF_FILE/REF_FIELD/SEQ/SUM/COUNT/RANDOM/EXPRESSION';
COMMENT ON COLUMN meta_field_definition.ref_field_key IS '引用的同报文内字段Key';
COMMENT ON COLUMN meta_field_definition.ref_enum_key IS '引用的枚举库Key';
COMMENT ON COLUMN meta_field_definition.ref_sequence_key IS '引用的序列号Key';
COMMENT ON COLUMN meta_field_definition.ref_file_id IS '引用的素材文件ID';
COMMENT ON COLUMN meta_field_definition.rule_config_json IS '包含金额DSL、表达式DSL、随机规则等';

CREATE INDEX idx_meta_field_definition_model_sort ON meta_field_definition (model_id, section, sort_index);

-- 15. 枚举库
DROP TABLE IF EXISTS meta_enum_library;
CREATE TABLE meta_enum_library (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  enum_key  VARCHAR(50)  NOT NULL,
  enum_name VARCHAR(100) DEFAULT NULL,
  items     JSONB        NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_meta_enum_library_enum_key UNIQUE (enum_key)
);

COMMENT ON TABLE meta_enum_library IS '枚举库';
COMMENT ON COLUMN meta_enum_library.id IS '主键ID';
COMMENT ON COLUMN meta_enum_library.enum_key IS '枚举唯一标识，如 sex';
COMMENT ON COLUMN meta_enum_library.enum_name IS '枚举名称/业务描述';
COMMENT ON COLUMN meta_enum_library.items IS '枚举项JSON: [{"val":"0", "desc":"男"}, {"val":"1", "desc":"女"}]';

-- 16. 引用素材文件
DROP TABLE IF EXISTS meta_ref_file;
CREATE TABLE meta_ref_file (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ref_name       VARCHAR(50)  NOT NULL,
  file_path      VARCHAR(255) NOT NULL,
  parse_type     VARCHAR(20)  NOT NULL,
  delimiter      VARCHAR(10)  DEFAULT NULL,
  column_mapping JSONB        DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uk_meta_ref_file_ref_name UNIQUE (ref_name)
);

COMMENT ON TABLE meta_ref_file IS '引用素材文件';
COMMENT ON COLUMN meta_ref_file.id IS '主键ID';
COMMENT ON COLUMN meta_ref_file.ref_name IS '引用名称/唯一标识';
COMMENT ON COLUMN meta_ref_file.file_path IS '素材文件路径';
COMMENT ON COLUMN meta_ref_file.parse_type IS '解析类型：DELIMITER / FIXED';
COMMENT ON COLUMN meta_ref_file.delimiter IS '分隔符内容';
COMMENT ON COLUMN meta_ref_file.column_mapping IS '列索引与Key映射: {"userName": 1, "age": 2}';

-- 17. 并发锁控与游标表
DROP TABLE IF EXISTS meta_sequence_tracker;
CREATE TABLE meta_sequence_tracker (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
  target_type   VARCHAR(20)  NOT NULL,
  target_id     VARCHAR(100) NOT NULL,
  current_value BIGINT       DEFAULT 0,
  update_time   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uk_meta_sequence_tracker_target UNIQUE (target_type, target_id)
);

COMMENT ON TABLE meta_sequence_tracker IS '并发锁控与游标表';
COMMENT ON COLUMN meta_sequence_tracker.id IS '主键ID';
COMMENT ON COLUMN meta_sequence_tracker.target_type IS '追踪类型：SEQ / REF_FILE';
COMMENT ON COLUMN meta_sequence_tracker.target_id IS '追踪目标标识: modelId:fieldKey 或 refFileId';
COMMENT ON COLUMN meta_sequence_tracker.current_value IS '当前值/游标位置';
COMMENT ON COLUMN meta_sequence_tracker.update_time IS '最后更新时间';

CREATE TRIGGER trg_meta_sequence_tracker_update_time
BEFORE UPDATE ON meta_sequence_tracker
FOR EACH ROW EXECUTE FUNCTION set_update_time();

-- 18. FTP配置表
DROP TABLE IF EXISTS meta_ftp_config;
CREATE TABLE meta_ftp_config (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(100) NOT NULL,
  ftp_ip      VARCHAR(100) NOT NULL,
  ftp_port    INTEGER      DEFAULT 21,
  username    VARCHAR(100) NOT NULL,
  password    VARCHAR(200) NOT NULL,
  remote_path VARCHAR(500) NOT NULL,
  create_user VARCHAR(50)  DEFAULT NULL,
  create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

COMMENT ON TABLE meta_ftp_config IS 'FTP配置表';
COMMENT ON COLUMN meta_ftp_config.id IS '主键ID';
COMMENT ON COLUMN meta_ftp_config.name IS '配置名称';
COMMENT ON COLUMN meta_ftp_config.ftp_ip IS 'FTP服务器IP';
COMMENT ON COLUMN meta_ftp_config.ftp_port IS 'FTP端口';
COMMENT ON COLUMN meta_ftp_config.username IS 'FTP用户名';
COMMENT ON COLUMN meta_ftp_config.password IS 'FTP密码';
COMMENT ON COLUMN meta_ftp_config.remote_path IS '远程目录路径';
COMMENT ON COLUMN meta_ftp_config.create_user IS '创建人';
COMMENT ON COLUMN meta_ftp_config.create_time IS '创建时间';
COMMENT ON COLUMN meta_ftp_config.update_time IS '最后修改时间';

CREATE TRIGGER trg_meta_ftp_config_update_time
BEFORE UPDATE ON meta_ftp_config
FOR EACH ROW EXECUTE FUNCTION set_update_time();

-- 19. 生成历史与任务表
DROP TABLE IF EXISTS meta_entity_file;
CREATE TABLE meta_entity_file (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  model_id     BIGINT       NOT NULL,
  file_name    VARCHAR(255) NOT NULL,
  file_type    VARCHAR(20)  NOT NULL,
  storage_path VARCHAR(255) NOT NULL,
  row_count    INTEGER      DEFAULT 0,
  status       VARCHAR(20)  DEFAULT 'RUNNING',
  create_user  VARCHAR(50)  DEFAULT NULL,
  create_time  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  duration_ms  INTEGER      DEFAULT NULL,
  error_msg    TEXT         DEFAULT NULL,
  temp_path    VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

COMMENT ON TABLE meta_entity_file IS '生成历史与任务表';
COMMENT ON COLUMN meta_entity_file.id IS '主键ID';
COMMENT ON COLUMN meta_entity_file.model_id IS '所属模型ID';
COMMENT ON COLUMN meta_entity_file.file_name IS '生成的文件名';
COMMENT ON COLUMN meta_entity_file.file_type IS '文件类型：PREVIEW / FORMAL';
COMMENT ON COLUMN meta_entity_file.storage_path IS '文件存储路径';
COMMENT ON COLUMN meta_entity_file.row_count IS '生成行数';
COMMENT ON COLUMN meta_entity_file.status IS '生成状态：SUCCESS/FAILED/RUNNING';
COMMENT ON COLUMN meta_entity_file.create_user IS '创建人';
COMMENT ON COLUMN meta_entity_file.create_time IS '创建时间';
COMMENT ON COLUMN meta_entity_file.duration_ms IS '生成耗时(毫秒)';
COMMENT ON COLUMN meta_entity_file.error_msg IS '错误信息';
COMMENT ON COLUMN meta_entity_file.temp_path IS '生成中的临时路径';
